// This file is auto-generated by @hey-api/openapi-ts

export type DtoGame = {
    gameMode?: string;
    id?: number;
    name?: string;
    players?: Array<DtoPlayer>;
    startingScore?: number;
};

export type DtoPlayer = {
    id?: number;
    name?: string;
};

export type ModelsGame = {
    gameMode?: string;
    id?: number;
    name?: string;
    players?: Array<ModelsPlayer>;
};

export type ModelsPlayer = {
    id?: number;
    username?: string;
};

export type GetApiGameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/game';
};

export type GetApiGameResponses = {
    /**
     * List of games
     */
    200: Array<ModelsGame>;
};

export type GetApiGameResponse = GetApiGameResponses[keyof GetApiGameResponses];

export type PostApiGameData = {
    /**
     * Game information
     */
    body: DtoGame;
    path?: never;
    query?: never;
    url: '/api/game';
};

export type PostApiGameErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiGameResponses = {
    /**
     * Created game
     */
    201: ModelsGame;
};

export type PostApiGameResponse = PostApiGameResponses[keyof PostApiGameResponses];

export type GetApiUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetApiUserResponses = {
    /**
     * List of players
     */
    200: Array<DtoPlayer>;
};

export type GetApiUserResponse = GetApiUserResponses[keyof GetApiUserResponses];

export type PostApiUserData = {
    /**
     * Player information
     */
    body: DtoPlayer;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type PostApiUserErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiUserResponses = {
    /**
     * Created player
     */
    201: DtoPlayer;
};

export type PostApiUserResponse = PostApiUserResponses[keyof PostApiUserResponses];

export type ClientOptions = {
    baseUrl: string;
};