// This file is auto-generated by @hey-api/openapi-ts

export type DtoGame = {
    gameMode?: string;
    id?: number;
    name?: string;
    players?: Array<DtoPlayer>;
    startingScore?: number;
};

export type DtoPlayer = {
    id?: number;
    name?: string;
};

export type ModelsGame = {
    gameMode?: string;
    id?: number;
    name?: string;
    players?: Array<ModelsPlayer>;
};

export type ModelsPlayer = {
    id?: number;
    username?: string;
};

export type GetApiGameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/game';
};

export type GetApiGameResponses = {
    /**
     * List of games
     */
    200: Array<ModelsGame>;
};

export type GetApiGameResponse = GetApiGameResponses[keyof GetApiGameResponses];

export type PostApiGameData = {
    /**
     * Game information
     */
    body: DtoGame;
    path?: never;
    query?: never;
    url: '/api/game';
};

export type PostApiGameErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiGameResponses = {
    /**
     * Created game
     */
    201: DtoGame;
};

export type PostApiGameResponse = PostApiGameResponses[keyof PostApiGameResponses];

export type GetApiPlayerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/player';
};

export type GetApiPlayerResponses = {
    /**
     * List of players
     */
    200: Array<DtoPlayer>;
};

export type GetApiPlayerResponse = GetApiPlayerResponses[keyof GetApiPlayerResponses];

export type PostApiPlayerData = {
    /**
     * Player information
     */
    body: DtoPlayer;
    path?: never;
    query?: never;
    url: '/api/player';
};

export type PostApiPlayerErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiPlayerResponses = {
    /**
     * Created player
     */
    201: DtoPlayer;
};

export type PostApiPlayerResponse = PostApiPlayerResponses[keyof PostApiPlayerResponses];

export type ClientOptions = {
    baseUrl: string;
};